class packetConfig:
    BYTES_PER_PACKET = 1500
    BYTES_PER_HEADER = 20
    DROP_PUNISHMENDT = 0.05

class logConfig:
    MAX_LINE_PER_FILE = 2000

class objectType:
    SENDER = 1
    ROUTER = 2

class eventType:
    DEBUG_STR = {
        1: "STOP_CHECKER",
        2: "BLOCK_EVENT_CREATE",
        3: "BLOCK_EVENT_ACK",
        4: "SOLUTION_SENDER_CC_EVENT_ACK",
        5: "SOLUTION_SENDER_CC_EVENT_DROP",
        6: "SOLUTION_SENDER_SCHE_EVENT",
        7: "SOLUTION_SENDER_CC_EVENT_SEND",
        8: "SOLUTION_SENDER_LABEL_EVENT",
        9: "SOLUTION_ROUTER_SCHE_EVENT_IN",
        10: "SOLUTION_ROUTER_SCHE_EVENT_OUT",
        11: "SOLUTION_ROUTER_LABEL_EVENT",
        12: "SENDER_EVENT",
        13: "ROUTER_PRE_SEND_EVENT",
        14: "ROUTER_SEND_EVENT",
        15: "PACKET_EVENT",
        16: "LOG_PACKET_EVENT",
    }
    STOP_CHECKER = 1
    BLOCK_EVENT_CREATE  = 2
    BLOCK_EVENT_ACK = 3
    SOLUTION_SENDER_CC_EVENT_ACK = 4
    SOLUTION_SENDER_CC_EVENT_DROP = 5
    SOLUTION_SENDER_SCHE_EVENT = 6
    SOLUTION_SENDER_CC_EVENT_SEND = 7
    SOLUTION_SENDER_LABEL_EVENT = 8
    SOLUTION_ROUTER_SCHE_EVENT_IN = 9
    SOLUTION_ROUTER_SCHE_EVENT_OUT = 10
    SOLUTION_ROUTER_LABEL_EVENT = 11
    SENDER_EVENT = 12
    ROUTER_PRE_SEND_EVENT = 13
    ROUTER_SEND_EVENT = 14
    PACKET_EVENT = 15
    LOG_PACKET_EVENT = 16